feat: jetpack compose demo
paypal/paypal-messages-android pull request #10
Opened 2023-10-19 19:10 UTC by grablack

## Description

## Screenshots

## Testing instructions

2024-02-05 14:54 UTC, merlinpaypal requested changes

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +fun ClientIdField(clientId: String, onChange: (text: String) -> Unit, text: String) {
I think it would be cleaner if we move each of these composables into a separate file.

Each of these text fields seem to have similar logic. Is there a way we can re-use similar code for them?

The Options functions also seem similar and so the Switch functions, so can we re-use similar code there?

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +fun LogoOptions(logoGroupOptions: List<String>, selected: String, onSelected: (text: String) -> Unit) {
Is it possible to simplify the logic used if `toSentenceCase` is used in the `Text` block and use the outright enum value in the rest of it? Something like

```
LogoOptions(logoGroupOptions: List<PayPalMessageLogoType>, selected: PayPalMessageLogoType, onSelected...)
  logoGroupOptions.forEach { enumValue ->
    ...
    RadioButton = (enumValue == selected)
    ...
    Text(text = toSentenceCase(enumValue.name)...)
    ...
```

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +						Row(
A Row container wasn't needed for `Style Options`. Is it necessary here?

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +				var progessBar by remember { mutableStateOf(false) }
I think this was meant to be `progressBar`

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +					if (PayPalMessageColor.valueOf(messageColor.uppercase()) === PayPalMessageColor.WHITE) {
The assignment can be extracted to make this more of a ternary with `backgroundColor = if(... === WHITE) Color.Black else Color.White`

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +					messageView.buyerCountry = buyerCountry.let {
We can make buyerCountry and amount assignments a little more Android-y by using `ifBlank` and `isNotBlank` like in XmlActivity

```
val amountString = amountEdit.text.toString()
val amount = if (amountString.isNotBlank()) amountString.toDouble() else null

val buyerCountry = buyerCountryEdit.text.toString().ifBlank { "US" }
```

2024-02-05 14:54 UTC, merlinpaypal commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +	return words.joinToString(" ") { it -> it.replaceFirstChar { it.titlecase() } }
Since this is only used on single word values, we can simplify this to `input.lowercase().replaceFirstChar { it.titlecase() }

2024-02-12 15:20 UTC, grablack commented on demo/src/main/java/com/paypal/messagesdemo/JetpackActivity.kt
> +						Row(
The button belongs in the row. I moved it back to match the XML demo

2024-02-12 21:30 UTC, merged