refactor: match minSdk from sdk
paypal/paypal-messages-android pull request #22
Opened 2024-01-17 19:54 UTC by grablack

## Description

## Screenshots

## Testing instructions

2024-02-05 14:54 UTC, merlinpaypal requested changes

2024-02-05 14:54 UTC, merlinpaypal commented on .github/workflows/test-release.yml
> +          distribution: 'temurin'
Use `microsoft` here and in `test_instrumentation`

2024-02-05 14:54 UTC, merlinpaypal commented on build.gradle
> +		"androidMinSdkVersion": 21,
Why the switch to 21? The PayPal Android SDK uses 23+.
https://github.com/paypal/paypal-android?tab=readme-ov-file#support

2024-02-12 16:25 UTC, grablack commented on build.gradle
> +		"androidMinSdkVersion": 21,
The main [gradle is set to 21](https://github.com/paypal/paypal-android/blob/main/build.gradle). [PayPalNativePayments](https://github.com/paypal/paypal-android/blob/main/PayPalNativePayments/build.gradle) has it set to 23 and the[ demo xml is overriding the project](https://github.com/paypal/paypal-android/blob/main/Demo/src/main/AndroidManifest.xml#L7) to use that. I believe that is why its listed as 23+. Dependencies use the gradle version so it wants 21 and I get this error when adding messaging at sdk version 23. Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.paypal.messages:paypal-messages...] as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 23

2024-04-03 15:52 UTC, grablack commented on .github/workflows/test-release.yml
> +          distribution: 'temurin'
changed

2024-04-03 15:52 UTC, grablack commented on build.gradle
> +		"androidMinSdkVersion": 21,
set to 23

2024-04-11 13:04 UTC, merlinpaypal approved these changes

2024-04-11 13:06 UTC, merged